"""
0001_initial.py

Este arquivo é uma migração gerada automaticamente pelo Django, responsável por criar a estrutura inicial do banco de dados para a aplicação de dashboard. Ele define os modelos que serão utilizados, especificando como as tabelas correspondentes devem ser criadas no banco de dados.

### Importância
A importância do `0001_initial.py` reside na sua função de estabelecer a base da estrutura do banco de dados. As migrações são fundamentais para manter a integridade dos dados e garantir que a aplicação possa evoluir ao longo do tempo sem perder informações. Este arquivo é o primeiro de uma série de migrações que podem ser aplicadas à medida que novas funcionalidades e modelos são adicionados ao projeto.

### Principais Componentes
Entre os principais componentes implementados neste arquivo, destacam-se:

1. **Classe `Migration`**: 
   - A classe `Migration` encapsula as operações que devem ser realizadas na migração do banco de dados. Este arquivo especifica que é a migração inicial (`initial = True`) e não tem dependências de migrações anteriores.

2. **Operação `migrations.CreateModel`**: 
   - Esta operação cria o modelo `AccessLog`, que contém os seguintes campos:
     - `id`: Um campo auto-incrementado que serve como chave primária da tabela.
     - `ip_address`: Um campo que armazena endereços IP, utilizando `GenericIPAddressField` para suportar IPv4 e IPv6.
     - `accessed_at`: Um campo que registra a data e hora em que o acesso ocorreu, sendo preenchido automaticamente na criação do registro.

Este arquivo é crucial para a inicialização do banco de dados e deve ser mantido de acordo com as alterações nos modelos da aplicação, garantindo que todas as mudanças sejam refletidas na estrutura do banco de dados.
"""

# Generated by Django 5.1 on 2024-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
